MyBlog/MyBlog/Models/Article.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBlog.Models
{
      public class Article
    {
        public int Id { get; set; }
        [Display(Name = "Datum publikace")]
        public DateTime PublicationDate { get; set; }
        [Display(Name = "Nadpis")]
        [Required(ErrorMessage = "Vyplňte Nadpis")]
        [StringLength(50, ErrorMessage = "Nadpis je příliš dlouhý(max. 50 znaků)")]
        public string Title { get; set; }
        [Display(Name = "Úvodní text")]
        [Required(ErrorMessage = "Vyplňte úvodní text")]
        [StringLength(100, ErrorMessage = "Úvodní text je příliš dlouhý(max. 100 znaků)")]
        public string OpenText{ get; set; }
        [Display(Name = "Text blogu")]
        [AllowHtml]// kvůli vložení HTML do "Text"
        [Required(ErrorMessage = "Vyplňte text")]
        public string Text { get; set; }
        [Display(Name = "Sekce")]
        public string Section { get; set; }

    }
        
    
}

MyBlog/MyBlog/Controllers/ArticleController.cs
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyBlog.Models;
using System.Dynamic;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace MyBlog.Controllers
{
    [Authorize(Roles = "admin")]
    public class ArticleController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Article
        [AllowAnonymous]
        public ActionResult Index()
        {
            //RoleManager<IdentityRole> spravceRoli = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new IdentityDbContext()));
            //spravceRoli.Create(new IdentityRole("admin"));
            //UserManager<ApplicationUser> spravceUzivatelu = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            //ApplicationUser uzivatel = spravceUzivatelu.FindByName("jiri.bardodej@seznam.cz");
            //spravceUzivatelu.AddToRole(uzivatel.Id, "admin");
            // klidně smaž
            

            return View(db.Articles.ToList());
        }
        [AllowAnonymous]
        // Filtruje články podle sekce
        public ActionResult FiltrSekce(string filtrsekce)
        {
            if(filtrsekce != null)
                {
                var filtrList = db.Articles
                                  .Where(r => r.Section == filtrsekce)
                                  .ToList();
                return View(filtrList);
                }
            return View();
        }

        // GET: Article/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (id == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // GET: Article/Create
        public ActionResult Create()
        {
            ViewBag.Sections = new SelectList(db.Sections, "Id", "Sekce");// Pro DropDownList
            return View();
        }

        // POST: Article/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,OpenText,Text,Section,Tags")] Article article)
        {
            if (ModelState.IsValid)
            {
                article.PublicationDate = DateTime.Now;//nastaví datum a čas publikace článku na PC datum a čas
                db.Articles.Add(article);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Sections = new SelectList(db.Sections, "Id", "Sekce");// Pro DropDownList
            return View(article);
        }

        // GET: Article/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Sections = new SelectList(db.Sections, "Id", "Sekce");// Pro DropDownList
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Article/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,OpenText,Text,Section,Tags")] Article article)
        {
            if (ModelState.IsValid)
            {
                article.PublicationDate = DateTime.Now;//nastaví datum a čas publikace článku na PC datum a čas
                db.Entry(article).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(article);
        }

        // GET: Article/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Article article = db.Articles.Find(id);
            if (article == null)
            {
                return HttpNotFound();
            }
            return View(article);
        }

        // POST: Article/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Article article = db.Articles.Find(id);
            db.Articles.Remove(article);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyBlog/MyBlog/Controllers/SectionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyBlog.Models;

namespace MyBlog.Controllers
{
    [Authorize(Roles = "admin")]//třídu smí používat jen admin
    public class SectionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Sections
        public ActionResult Index()
        {
            return View(db.Sections.ToList());
        }

        // GET: Sections/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // GET: Sections/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sections/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Sekce")] Section section)
        {
            if (ModelState.IsValid)
            {
                db.Sections.Add(section);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(section);
        }

        // GET: Sections/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Sections/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Sekce")] Section section)
        {
            if (ModelState.IsValid)
            {
                db.Entry(section).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(section);
        }

        // GET: Sections/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Section section = db.Sections.Find(id);
            if (section == null)
            {
                return HttpNotFound();
            }
            return View(section);
        }

        // POST: Sections/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Section section = db.Sections.Find(id);
            db.Sections.Remove(section);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyBlog/MyBlog/Views/Article/Create.cshtml
@model MyBlog.Models.Article

@{
    ViewBag.Title = "Vytvoř nový Blog";
}
@section Scripts
{
    <script src="@Url.Content("//tinymce.cachefly.net/4.0/tinymce.min.js")"></script>
    <script src="@Url.Content("~/Scripts/initTinyMCE.js")"></script>
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nový Blog</h4>
        <hr />
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Section, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Section, new SelectList(ViewBag.Sections, "Text","Text"), new { @class = "form-control"})
                @*<p>
                    @Html.ActionLink("+ nová sekce", "Create", "Sections")
                </p>*@
                @Html.ValidationMessageFor(model => model.Section, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.OpenText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Vytvoř" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zpět na Blog", "Index")
</div>

MyBlog/MyBlog/Views/Article/Delete.cshtml
@model MyBlog.Models.Article

@{
    ViewBag.Title = "Vymaž článek";
}
<h3>Opravdu chce odstranit článek "@Html.DisplayFor(model => model.Title)"?</h3>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Vymazat článek" class="btn btn-default" /> |
            @Html.ActionLink("Zpět na Blog", "Index")
        </div>
    }

MyBlog/MyBlog/Views/Article/Details.cshtml
@model MyBlog.Models.Article

@{
    ViewBag.Title = "Detail článku";
}

<h2>Detail článku</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PublicationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublicationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.Raw(Model.Text) @*přepsáno z DisplayFor na RAW , neprovádí se převod HTML enti., možno vkládat HTML code.*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Section)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Section)
        </dd>
        

    </dl>
</div>
<p>
    @if (User.IsInRole("admin"))
    {
    @Html.ActionLink("Upravit", "Edit", new { id = Model.Id })
    @:| 
    }

    @Html.ActionLink("Zpět na Blog", "Index")
</p>

MyBlog/MyBlog/Views/Article/Edit.cshtml
@model MyBlog.Models.Article

@{
    ViewBag.Title = "Uprav článek";
}
@section Scripts
{
    <script src="@Url.Content("//tinymce.cachefly.net/4.0/tinymce.min.js")"></script>
    <script src="@Url.Content("~/Scripts/initTinyMCE.js")"></script>
}

<h2>Úprava článku</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Section, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Section, new SelectList(ViewBag.Sections,"Text","Text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Section, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.OpenText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OpenText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OpenText, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>
</div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Uložit" class="btn btn-default" />
            </div>
        </div>
    
}

<div>
    @Html.ActionLink("Zpět na Blog", "Index")
</div>

MyBlog/MyBlog/Views/Article/FiltrSekce.cshtml
@model IEnumerable<MyBlog.Models.Article>
@{
    ViewBag.Title = "Sekce";
}

<h2>Filtr sekce</h2>

    <hr />
  <body>

      @foreach (var item in Model)
      {
          {
            <h2 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h2>
            <p class="card-text">@Html.DisplayFor(modelItem => item.OpenText)</p>
            <a href="@Url.Action("Details", "Article", new { id = item.Id })" class="btn btn-primary">Přečíst více &rarr;</a>
            <p>
                @if (User.IsInRole("admin"))
                    {
                       @Html.ActionLink("Upravit", "Edit", new { id = item.Id })
                       @:| 
                       @Html.ActionLink("Smazat", "Delete", new { id = item.Id })
                    }
            </p>
                <div class="card-footer text-muted">Uveřejněno @Html.DisplayFor(modelItem => item.PublicationDate)</div>
          }
      }
      <p>
          @Html.ActionLink("Zpět na Blog", "Index")
      </p>
  </body>  
        

MyBlog/MyBlog/Views/Article/Index.cshtml
@model IEnumerable<MyBlog.Models.Article>

@{
    ViewBag.Title = "Blog";
}
<body>

@foreach (var item in Model)
    {
        <h2 class="card-title">@Html.DisplayFor(modelItem => item.Title)</h2>
        <p class="card-text">@Html.DisplayFor(modelItem => item.OpenText)</p>
            <a href="@Url.Action("Details", "Article", new { id = item.Id })" class="btn btn-primary">Přečíst více &rarr;</a>
                <p>
                    @if (User.IsInRole("admin"))
                    {
                        @Html.ActionLink("Upravit", "Edit", new { id = item.Id })
                        @:| 
                        @Html.ActionLink("Smazat", "Delete", new { id = item.Id })
                    }
                </p>
        <div class="card-footer text-muted">Uveřejněno @Html.DisplayFor(modelItem => item.PublicationDate)</div>
    }
</body>

@section SideBar{
     
<div class="card my-4">
<h5 class="card-header">Sekce</h5>
<div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                         @foreach (var item in Model.Select(x=> x.Section).Distinct())
                         {
                            <li>
                                 @Html.ActionLink(item, "FiltrSekce", "Article", new { filtrSekce = item }, null)
                            </li>
                         }
                    </ul>
                </div>
            </div>
</div>
</div>
}
@if (User.IsInRole("admin"))
{
@section SideBarAdmin{

<div class="card my-4">
<h5 class="card-header">Administrace obsahu blogu</h5>
<div class="card-body">
    <div class="row">
        <div class="col-lg-6">
            <ul class="list-unstyled mb-0">
                <li>
                    @Html.ActionLink("Vytvořit nový článek", "Create")
                </li>
                <li>
                    @Html.ActionLink("Správce sekcí", "index", "Sections")
                </li>
            </ul>
        </div>
    </div>
</div>
</div>
}
}